import { useEffect, useState } from 'react'
import type { PerformanceSummary, Telemetry } from '../types/simulation'

export function Events({ state }: { state: Telemetry }) { return <section className="panel events"><header className="panel-head"><div><span className="eyebrow">Persistent session stream</span><h2>Live event log</h2></div><span>{state.events.length} events</span></header><div className="event-list">{state.events.length === 0 ? <p>No event yet. Start the simulation to record telemetry.</p> : [...state.events].reverse().map((event, index) => <article key={`${event.timestamp}-${index}`}><time>{event.timestamp.toFixed(2)}s</time><span className={event.category}>{event.category}</span><p>{event.message}</p></article>)}</div></section> }

async function generate(sessionId: string): Promise<string> { const response = await fetch(`/api/performance/${sessionId}/generate-pdf`, { method: 'POST' }); if (!response.ok) throw new Error(await response.text()); const payload = await response.json() as { pdf: string }; return payload.pdf }

export function Reports({ state, onError }: { state: Telemetry; onError: (message: string) => void }) {
  const [sessions, setSessions] = useState<PerformanceSummary[]>([])
  const [loading, setLoading] = useState(false)
  const refresh = async () => { try { const response = await fetch('/api/performance/sessions'); if (!response.ok) throw new Error('Could not load session history.'); setSessions(await response.json() as PerformanceSummary[]) } catch (error) { onError(error instanceof Error ? error.message : 'Session history failed.') } }
  useEffect(() => { void refresh() }, [])
  const makeReport = async () => { setLoading(true); try { const url = await generate(state.performance.session_id); await refresh(); window.open(url, '_blank', 'noopener,noreferrer') } catch (error) { onError(error instanceof Error ? error.message : 'PDF report generation failed.') } finally { setLoading(false) } }
  const sessionRows = sessions.filter((session) => session.session_id !== state.performance.session_id)
  return <section className="panel reports"><header className="panel-head"><div><span className="eyebrow">CSV / PDF exports</span><h2>Performance reporting</h2></div><span>Session {state.performance.session_id || 'pending'}</span></header><div className="report-summary"><span>Duration <strong>{state.performance.duration?.toFixed(1) ?? 0}s</strong></span><span>Frames <strong>{state.performance.total_frames_processed ?? 0}</strong></span><span>Target losses <strong>{state.performance.target_loss_count ?? 0}</strong></span></div><div className="report-actions"><button className="action primary" disabled={loading || !state.running && state.performance.duration === 0} onClick={() => void makeReport()}>{loading ? 'Generating…' : 'Generate PDF report'}</button><a className="action" href={`/api/performance/${state.performance.session_id}/csv`} download>Download CSV</a><button className="action muted" onClick={() => void refresh()}>Refresh sessions</button></div><div className="session-list"><h3>Previous sessions</h3>{sessionRows.length === 0 ? <p>Completed sessions appear after Reset or report generation.</p> : sessionRows.slice(0, 5).map((session) => <article key={session.session_id}><div><strong>{session.session_id}</strong><span>{session.duration?.toFixed(1)}s · {session.average_fps?.toFixed(1)} FPS · {session.average_tracking_error?.toFixed(1)} px</span></div><div><a href={`/api/performance/${session.session_id}/csv`} download>CSV</a><a href={`/api/performance/${session.session_id}/pdf`} target="_blank" rel="noreferrer">PDF</a></div></article>)}</div></section>
}
