import { useEffect, useState } from 'react'
import type { AppConfig, Command, DeepPartial, Telemetry } from '../types/simulation'

type Scenario = { name: string; saved_at: string; config: AppConfig }

function NumberControl({ label, value, min, max, step, suffix = '', onChange }: { label: string; value: number; min: number; max: number; step: number; suffix?: string; onChange: (value: number) => void }) {
  return <label className="setting-row"><span>{label}<small>{value.toFixed(step < 1 ? 2 : 0)}{suffix}</small></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>
}

export function ScenarioSettings({ state, send, onError }: { state: Telemetry; send: (value: Command) => void; onError: (message: string) => void }) {
  const [scenarios, setScenarios] = useState<Scenario[]>([])
  const [name, setName] = useState('')
  const [busy, setBusy] = useState(false)
  const update = (config: DeepPartial<AppConfig>) => send({ action: 'configure', config })
  const refresh = async () => { try { const response = await fetch('/api/scenarios'); if (!response.ok) throw new Error('Unable to load saved scenarios.'); setScenarios(await response.json() as Scenario[]) } catch (error) { onError(error instanceof Error ? error.message : 'Unable to load scenarios.') } }
  useEffect(() => { void refresh() }, [])
  const save = async () => { const trimmed = name.trim(); if (!trimmed) { onError('Enter a scenario name before saving.'); return } setBusy(true); try { const response = await fetch(`/api/scenarios/${encodeURIComponent(trimmed)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(state.config) }); if (!response.ok) throw new Error(await response.text()); setName(''); await refresh() } catch (error) { onError(error instanceof Error ? error.message : 'Unable to save scenario.') } finally { setBusy(false) } }
  const load = async (scenario: Scenario) => { send({ action: 'configure', config: scenario.config }) }
  const remove = async (scenario: Scenario) => { try { const response = await fetch(`/api/scenarios/${encodeURIComponent(scenario.name)}`, { method: 'DELETE' }); if (!response.ok) throw new Error(await response.text()); await refresh() } catch (error) { onError(error instanceof Error ? error.message : 'Unable to delete scenario.') } }
  return <section className="settings-layout"><section className="panel settings-panel"><header className="panel-head"><div><span className="eyebrow">Authoritative simulation configuration</span><h2>Scenarios / simulation settings</h2></div><span className="status-tag">{state.simulation.active_pattern.toUpperCase()}</span></header><div className="settings-columns">
    <div><h3>Primary trajectory</h3><NumberControl label="Range" value={state.config.motion.distance} min={45} max={230} step={1} suffix=" m" onChange={(value) => update({ motion: { distance: value } })} /><NumberControl label="Altitude" value={state.config.motion.altitude} min={3} max={70} step={1} suffix=" m" onChange={(value) => update({ motion: { altitude: value } })} /><NumberControl label="Path radius" value={state.config.motion.radius} min={5} max={90} step={1} suffix=" m" onChange={(value) => update({ motion: { radius: value } })} /><NumberControl label="Pattern speed" value={state.config.motion.speed} min={.2} max={3} step={.1} onChange={(value) => update({ motion: { speed: value } })} /></div>
    <div><h3>Virtual camera / controller</h3><NumberControl label="Horizontal FOV" value={state.config.camera.fov_horizontal} min={8} max={80} step={1} suffix="°" onChange={(value) => update({ camera: { fov_horizontal: value } })} /><NumberControl label="Vertical FOV" value={state.config.camera.fov_vertical} min={6} max={60} step={1} suffix="°" onChange={(value) => update({ camera: { fov_vertical: value } })} /><NumberControl label="Gimbal max rate" value={state.config.camera.max_rate} min={15} max={120} step={1} suffix="°/s" onChange={(value) => update({ camera: { max_rate: value } })} /><NumberControl label="Alignment threshold" value={state.config.camera.alignment_threshold} min={.4} max={5} step={.1} suffix="°" onChange={(value) => update({ camera: { alignment_threshold: value } })} /></div>
    <div><h3>Environment</h3><NumberControl label="Optical noise" value={state.config.disturbances.sensor_noise} min={0} max={.35} step={.01} onChange={(value) => update({ disturbances: { sensor_noise: value } })} /><NumberControl label="Vibration amplitude" value={state.config.disturbances.vibration.amplitude} min={0} max={.5} step={.01} onChange={(value) => update({ disturbances: { vibration: { amplitude: value } } })} /><NumberControl label="Auto pattern interval" value={state.config.motion.switch_interval} min={5} max={40} step={1} suffix=" s" onChange={(value) => update({ motion: { switch_interval: value } })} /><label className="check-row setting-check"><span>Enable geometry obstacle</span><input type="checkbox" checked={state.config.environment.obstacle_enabled} onChange={(event) => update({ environment: { obstacle_enabled: event.target.checked } })} /></label></div>
  </div></section>
  <section className="panel scenario-library"><header className="panel-head"><div><span className="eyebrow">Persistent local scenario library</span><h2>Save / load configuration</h2></div><button className="scene-toggle" onClick={() => void refresh()}>Refresh</button></header><div className="scenario-save"><input value={name} maxLength={48} onChange={(event) => setName(event.target.value.replace(/[^A-Za-z0-9_-]/g, ''))} placeholder="scenario_name" /><button className="action primary" disabled={busy} onClick={() => void save()}>{busy ? 'Saving...' : 'Save scenario'}</button><button className="action muted" onClick={() => send({ action: 'reset_defaults' })}>Reset defaults</button></div><div className="scenario-list">{scenarios.length === 0 ? <p>No saved scenario yet. Save the current controls to make one reusable.</p> : scenarios.map((scenario) => <article key={scenario.name}><div><strong>{scenario.name}</strong><span>{new Date(scenario.saved_at).toLocaleString()} · {scenario.config.motion.pattern} · {scenario.config.simulation.decoy_count} decoys</span></div><div><button className="scene-toggle" onClick={() => void load(scenario)}>Load</button><button className="scene-toggle danger" onClick={() => void remove(scenario)}>Delete</button></div></article>)}</div></section></section>
}
